VendingMachineWebMVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.AdapterProduct;
using BusinessLayer.Interfaces;
using BusinessLayer.Services;
using DataAccess;
using DataAccess.Models;
using DataAccess.Repositories;
using DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stripe;
using VendingMachineWebMVC.Models;


namespace VendingMachineWebMVC.Controllers
{
    public class ProductsController : Controller
    {
       // private IProductsRepository repo = new ProductRepository();
       // private IProductService productService = new BusinessLayer.Services.ProductService();
        private IHostingEnvironment HostingEnvironment;

        DataContext context = new DataContext();

        public ProductsController(IHostingEnvironment hostingEnvironment)
        {
            HostingEnvironment = hostingEnvironment;
        }
   
    // GET: Products
        public ActionResult Index()
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);

            ViewBag.products = target.Products;

           return View();
        }

        [Authorize(Roles = "Admin")]
         public IActionResult AddProduct()
         {
            return View();
         }

        [HttpPost]
        public IActionResult AddProduct(AddProductViewModel db)
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);

            string stringFileName = UploadFile(db);
            var product = new Products()
            {
                Name = db.Name,
                Price = db.Price,
                ItemsLeft = db.ItemsLeft,
                ItemsSold = db.ItemsSold,
                Image = stringFileName
            };

            target.AddProduct(product);

            return View();
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);
            await  target.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        
        private string UploadFile(AddProductViewModel db)
        {
            string fileName = null;
            if (db.Image != null)
            {
                string uploadDir = Path.Combine(HostingEnvironment.WebRootPath, "Images");
                fileName = Guid.NewGuid().ToString() + "-" + db.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    db.Image.CopyTo(fileStream);
                }
            }
            return fileName;
        }
    }

}

VendingMachineWebMVC/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BusinessLayer.Interfaces;
using BusinessLayer.Services;
using DataAccess.Repositories;
using DataAccess.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Scrypt;
using VendingMachineWebMVC.Models;


namespace VendingMachineWebMVC.Controllers
{
    public class UsersController : Controller
    {
        private IUserService userService = new UserService();
        private IUserRepository repo = new UserRepository();
        ClaimsIdentity identity = null;
        
        private const string secretCode = "ghujllrt";


        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(UserRegisterViewModel user)
        {

            var newUser = repo.FindUser(user.UserName);

            if (newUser != null)
            {
                ModelState.AddModelError("", "This username already exists");
                return View();
            }
            else
            {
                if (user.SecretCode == secretCode)
                {
                    userService.Register(user);
                }
                else
                {
                    ModelState.AddModelError("", "This secret code is not available");
                    return View();
                }
            }

            return View();
        }
        
        public IActionResult Login()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Login(DataAccess.ViewModels.UserLoginViewModel user)
        {
            ScryptEncoder encoder = new ScryptEncoder();
            bool isAuthenticated = false;
            var founduser = repo.FindUser(user.Username);
            
            if (founduser == null)
            {
                ModelState.AddModelError("", "Ths user does not exist");
            }
            else
            {

                bool isValidAdmin = encoder.Compare(user.Password, founduser.Password);

                if (isValidAdmin)
                {
                    identity = new ClaimsIdentity(new[] {
                    new Claim(ClaimTypes.Name, user.Username),
                    new Claim(ClaimTypes.Role, "Admin")
                }, CookieAuthenticationDefaults.AuthenticationScheme);
                    isAuthenticated = true;
                    if (isAuthenticated)
                    {
                        var principal = new ClaimsPrincipal(identity);

                        var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                        return RedirectToAction("Index", "Home");
                    }

                    else
                    {
                        ModelState.AddModelError("", "Check the password");
                    }
                }
            }
            return View();
        }
        
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index","Home");

        }
    }
}

VendingMachineWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VendingMachineWebMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VendingMachineWebMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Products" asp-action="Index">View Items</a>
                        </li>
                        
                        
                    </ul>
                    @if (!User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Register">
                                    Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login Here</a>
                            </li>
                        </ul>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                Welcome @Context.User.Identity.Name
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - VendingMachineWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>