VendingMachineWebMVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.AdapterProduct;
using BusinessLayer.Interfaces;
using BusinessLayer.Services;
using DataAccess;
using DataAccess.Models;
using DataAccess.Repositories;
using DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stripe;
using VendingMachineWebMVC.Models;


namespace VendingMachineWebMVC.Controllers
{
    public class ProductsController : Controller
    {
       // private IProductsRepository repo = new ProductRepository();
       // private IProductService productService = new BusinessLayer.Services.ProductService();
        private IHostingEnvironment HostingEnvironment;

        DataContext context = new DataContext();

        public ProductsController(IHostingEnvironment hostingEnvironment)
        {
            HostingEnvironment = hostingEnvironment;
        }
   
    // GET: Products
        public ActionResult Index()
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);

            ViewBag.products = target.Products;

           return View();
        }

        [Authorize(Roles = "Admin")]
         public IActionResult AddProduct()
         {
            return View();
         }

        [HttpPost]
        public IActionResult AddProduct(AddProductViewModel db)
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);

            string stringFileName = UploadFile(db);
            var product = new Products()
            {
                Name = db.Name,
                Price = db.Price,
                ItemsLeft = db.ItemsLeft,
                ItemsSold = db.ItemsSold,
                Image = stringFileName
            };

            target.AddProduct(product);

            return View();
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);
            await  target.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        
        private string UploadFile(AddProductViewModel db)
        {
            string fileName = null;
            if (db.Image != null)
            {
                string uploadDir = Path.Combine(HostingEnvironment.WebRootPath, "Images");
                fileName = Guid.NewGuid().ToString() + "-" + db.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    db.Image.CopyTo(fileStream);
                }
            }
            return fileName;
        }
    }

}

VendingMachineWebMVC/Controllers/ShoppingBasketItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess;
using DataAccess.Models;
using VendingMachineWebMVC.Helpers;
using DataAccess.Repositories;
using Stripe;
using BusinessLayer.Interfaces;
using BusinessLayer.AdapterProduct;

namespace VendingMachineWebMVC.Controllers
{
    public class ShoppingBasketItemsController : Controller
    {
       
       // private IProductsRepository repo = new ProductRepository();

        //private IProductService productservice = new BusinessLayer.Services.ProductService();

        public IActionResult Index()
        {
            var basket = SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket");

            ViewBag.basket = basket;
            ViewBag.total = basket.Sum(item => item.Product.Price * item.Quantity);

            return View();
        }
        
        public IActionResult BuyProduct(int id)
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);

            var product = target.find(id);

            if (SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket") == null)
            {

                List<ShoppingBasketItem> basket = new List<ShoppingBasketItem>
                {
                    new ShoppingBasketItem
                    {
                        Product = repo.find(id),
                        Quantity = 1
                    }
                };
                
                product.ItemsLeft--;
                product.ItemsSold++;
                
                SessionHelper.SetObjectAsJson(HttpContext.Session, "basket", basket);
            }

            else
            {
                List<ShoppingBasketItem> basket = SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket");
                int index = isExist(id);
                if (index != -1)
                {
                    List<Products> products = target.Products.ToList();
                    basket[index].Quantity++;
                }
                else
                {
                    basket.Add(new ShoppingBasketItem { Product = repo.find(id), Quantity = 1 });
                }
                
                product.ItemsLeft--;
                product.ItemsSold++;
                SessionHelper.SetObjectAsJson(HttpContext.Session, "basket", basket);

               
            }
            repo.Update(product);
            return RedirectToAction("Index");
        }
     

        public IActionResult Remove(int id)
        {
            ProductRepository repo = new ProductRepository();
            IProductsRepository target = new ProductAdapter(repo);
            List<ShoppingBasketItem> basket = SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket");
            int index = isExist(id);
            var product = target.find(id);
            if (basket[index].Quantity > 1)
            {
                basket[index].Quantity--;
                product.ItemsLeft++;
                product.ItemsSold--;
            }
            else if (basket[index].Quantity == 1)
            {
                basket.RemoveAt(index);
                product.ItemsLeft++;
                product.ItemsSold--;

            }

            repo.Update(product);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "basket", basket);
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<ShoppingBasketItem> basket = SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket");
            for (int i = 0; i < basket.Count; i++)
            {
                if (basket[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        


        private double GetTotal()
        {

            List<ShoppingBasketItem> basket = SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket");

            double total = basket.Sum(item => item.Product.Price * item.Quantity);

            return total;
        }

        private int GetQuantity()
        {
            List<ShoppingBasketItem> basket = SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket");
           
            int quantity = basket.Sum(item => item.Quantity);
            

            return quantity;
        }

        public IActionResult Purchase()
        {

            ViewBag.total = GetTotal();

            return View();
        }
        [HttpPost]
        public IActionResult Create(string stripeToken, int Id)
        {
            List<ShoppingBasketItem> basket = SessionHelper.GetObjectFromJson<List<ShoppingBasketItem>>(HttpContext.Session, "basket");
            
            double d = GetTotal();

            var chargeOptions = new ChargeCreateOptions()
            {
                Amount = (long)d * 100,
                Currency = "ron",
                Source = stripeToken,
            };

            var service = new ChargeService();
            Charge charge = service.Create(chargeOptions);

            if (charge.Status == "succeeded")
            {
               
                return View("Success");
                
            }

            return View("Failure");

        }
    }
}

VendingMachineWebMVC/Views/Products/AddProduct.cshtml
@model DataAccess.ViewModels.AddProductViewModel

@{
    ViewData["Title"] = "AddProduct";
}

<h1>AddProduct</h1>

<h4>Products</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProduct" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemsLeft" class="control-label"></label>
                <input asp-for="ItemsLeft" class="form-control" />
                <span asp-validation-for="ItemsLeft" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemsSold" class="control-label"></label>
                <input asp-for="ItemsSold" class="form-control" />
                <span asp-validation-for="ItemsSold" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

VendingMachineWebMVC/Views/Products/Index.cshtml
@model IEnumerable<DataAccess.Models.Products>

@{
    ViewData["Title"] = "Index";
}

<h1>Our Products</h1>
<p>

</p>
<div>
    @if (User.IsInRole("Admin"))
     {
        <a class="btn btn-outline-success" asp-controller="Products" asp-action="AddProduct">Add a new product</a>
     }
</div>
<p>

</p>
<div class="row">
    @foreach (var item in ViewBag.products)
    {
        @if (item.ItemsLeft > 0)
        {
            <div class="col-4">
                <div class="card">
                    <img class="card-img-top" src="~/Images/@item.Image" height="220" width="100" asp-append-version="true" />
                    <div class="card-body">
                        <h4 class="card-title">@item.Name</h4>
                        <p class="card-text">@(item.Price) Lei</p>

                    </div>
                    <div class="addToCart text-right">
                        <p class="button ">

                            <a class="btn btn-success" id="cartButton" asp-controller="ShoppingBasketItems" asp-action="BuyProduct" asp-route-Id="@item.Id">Buy Now </a>

                        </p>
                        <p>
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="btn btn-danger" id="cartButton" asp-controller="Products" asp-action="Delete" asp-route-Id="@item.Id" onclick="return confirm('Are you sure you want to delete this item?')">Delete Now </a>
                            }


                        </p>
                    </div>
                </div>
            </div>
        }
    }
   
</div>